apiVersion: v1
kind: Pod
metadata:
  name: seccomp-restricted-pod
  namespace: security-context
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
