apiVersion: v1
kind: Pod
metadata:
  name: uid-gid-pod
  namespace: security-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "id && sleep 3600"]
