# bad-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deploy
  namespace: psa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      containers:
      - name: nginx
        image: nginx
        securityContext:
          privileged: true
