apiVersion: v1
kind: Pod
metadata:
  name: busybox-debugger
  namespace: ops
spec:
  automountServiceAccountToken: false
  containers:
    - name: debug
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        privileged: false
