apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cks-02-opa-gatekeeper
  namespace: argocd
  annotations:
    cks.exercise: "02-opa-gatekeeper"
    cks.objective: "Implement policy enforcement with OPA Gatekeeper"
    cks.difficulty: "intermediate"
    cks.time: "45 minutes"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    category: security
    component: cks-lab
    policy-engine: gatekeeper
spec:
  project: default
  source:
    repoURL: https://github.com/open-policy-agent/gatekeeper
    targetRevision: release-3.15
    path: deploy/gatekeeper
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true