apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 13-sa-testing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: Sync
spec:
  project: default
  source:
    repoURL: https://github.com/planb438/Kubernetes.git
    targetRevision: HEAD
    path: gitops/clusters/cks-lab/manifests/13-sa-abuse-prevention/testing
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-security-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true