apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 13-sa-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/planb438/Kubernetes.git
    targetRevision: main
    path: gitops/clusters/cks-lab/manifests/13-sa-abuse-prevention/monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-security-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true