apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 14-task-02-audit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/planb438/Kubernetes.git
    targetRevision: HEAD
    path: gitops/clusters/cks-lab/manifests/14-mock-tasks/tasks/task-02-audit-logging
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mock-exam-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true