apiVersion: v1
kind: Pod
metadata:
  name: no-tmp-write
  annotations:
    container.apparmor.security.beta.kubernetes.io/app: localhost/deny-tmp
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "touch /tmp/test.txt || echo DENIED"]
