apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-read
  namespace: task1
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: task1
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
