apiVersion: v1
kind: Pod
metadata:
  name: risky-pod
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
  volumes:
    - name: host-vol
      hostPath:
        path: /etc
