apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restrict-view
  namespace: sa-test
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-sa
  namespace: sa-test
subjects:
- kind: ServiceAccount
  name: no-token
  namespace: sa-test
roleRef:
  kind: Role
  name: restrict-view
  apiGroup: rbac.authorization.k8s.io
